server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/netflix_micro_service_auth
    username: postgres
    password: p0stgr3s
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

security:
  jwt:
    token:
      secret-key: 5beb16f6-e98a-4366-85a6-69ddbd682cb7
      expires-in: 360000

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka